### ISSUE TITLE
Method not found: 'Boolean FolkerKinzel.Strings.ReadOnlySpanPolyfillExtension.Contains(System.ReadOnlySpan`1<Char>, Char)'

### ISSUE THREAD

**Issue by DustyRah** [FolkerKinzel/VCards#11]
**Describe the bug**
I see that the FolkerKinzel.Strings.ReadOnlySpanPolyfillExtension.Contains is not available in .NET 6.0. I am trying to convert IEnumerable<FolkerKinzel.VCards.VCard> to a List or at least obtain the first vCard from the set. But I get this error and am not able to move forward.
Method not found: 'Boolean FolkerKinzel.Strings.ReadOnlySpanPolyfillExtension.Contains(System.ReadOnlySpan`1<Char>, Char)'.
Stacktrace:
   at FolkerKinzel.VCards.VCard..ctor(Queue`1 queue, VcfDeserializationInfo info, VCdVersion versionHint)
   at FolkerKinzel.VCards.VcfReader.EnumerateVCards(TextReader reader, VCdVersion versionHint)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

**To Reproduce**
Code to reproduce the behavior:
string vCard = "";
using(TextReader stringReader = new StringReader(vcard))
{
  using (var vcfReader = new VcfReader(stringReader))
  {
    IEnumerable<FolkerKinzel.VCards.VCard> result = vcfReader.ReadToEnd();

    var parsedVCard = result.First();
  }
}

**Expected behavior**
We should be able to obtain the list of VCard object.

**Desktop (please complete the following information):**
 - .NET Version: .NET 6.0

**Additional context**
I am attempting to convert a vcard in string format into VCard object.

**Comment by FolkerKinzel** [comment]
Thank you for posting this issue.

The issue seems to be caused by a dependency binding problem: the application binds to the .NET Standard 2.1 version of `FolkerKinzel.VCards` which is built against the .NET Standard 2.1 version of `FolkerKinzel.Strings` but your application picks the .NET 6.0 version of `FolkerKinzel.Strings`. The problem is caused by the `FolkerKinzel.Strings` dependency.

As soon as possible I will try to fix this. In the meantime try the following workarounds:
- Try to upgrade your application to .NET 8.0.
- If this is not possible: Put all the stuff you do with `FolkerKinzel.VCards` in a separate  .NET Standard 2.1 DLL and don't reference `FolkerKinzel.Strings` from anywhere else in your application.

**Comment by FolkerKinzel** [comment]
Hi @DustyRah,

version 7.2.2 is published on nuget and fixes the `MethodNotFound` issue. The following code runs with .NET 6.0 properly now:
```csharp
using System.Text;
using FolkerKinzel.VCards;

string vcf = new StringBuilder()
   .AppendLine("BEGIN:VCARD")
   .AppendLine("VERSION:3.0")
   .AppendLine("FN:Folker")
   .AppendLine("END:VCARD")
   .ToString();

using TextReader stringReader = new StringReader(vcf);
using var vcfReader = new VcfReader(stringReader);

IEnumerable<VCard> result = vcfReader.ReadToEnd();

VCard parsedVCard = result.First();

Console.WriteLine(parsedVCard);
```
When parsing an empty string - like your example does - the `Enumerable.Find()` method will still throw an `InvalidOperationException` because the IEnumerable is empty in this case. To avoid this, call
```csharp
VCard? parsedVCard = result.FirstOrDefault();
```
or (to retrieve the (empty) `List<VCard`):
```csharp
var parsedVCards = result.ToList();
```

(Tip: Have a look at [the methods of the `Vcf` class](https://folkerkinzel.github.io/VCards/reference/html/776cc866-d81c-94ea-6b2e-9256ed03ad3b.htm): Only in a few special cases (e.g., ultra-large VCF files) is it advantageous to use `VcfReader` directly.)
