### ISSUE TITLE
CHARSETS not handled correctly

### ISSUE THREAD

**Issue by HeinzKessler** [FolkerKinzel/VCards#4]
First of all: Thank you for your effort!

VCFs that contain fields that are encoded with a certain CHARSET cannot be read correctly, because the extended characters got lost already when the vcf file was loaded by your code. Although the LoadVcf and ParseVcf methods have an optional encoding parameter, but this would mean that I had to guess the correct CHARSET in advance.

The VCards code should accept and process CHARSET parameters, so that fields with CHARSET are read with the correct encoding

My workaround was to read the Vcf into memory as a string, search for "CHARSET=" anywhere and read teh value afterwards (e.g. "Windows-1252". Then I open the file again using this encoding. This assumes that multiple CHARSET parameters in the same file all use the same encoding.

**Comment by FolkerKinzel** [comment]
Thanks for posting the issue. 

The CHARSET parameter exists only in vCard 2.1. It's use is normally to specify, how the hexadecimal values in the quoted-printable-encoding have to be interpreted. It seems you have to deal with vCard 2.1- vCards which use NON-ASCII characters without quoted-printable-encoding (ENCODING=8BIT). 

Am I right? Could you post the parameter part of such a vCard-row?

I want to try if it is possible to repair such fields automatically after being read with the wrong encoding and will provide a solution, if it's possible. It will take a few weeks because I'm very busy in the moment.

Meanwhile you could use the library for this workaround:

- Load the the vCard with VCard.LoadVcf("YourFilename.vcf") as UTF-8.
- Use Linq on the VCard object to determine, whether a VCardProperty object exists in it, which has VCardProperty.Parameters.Charset not null **AND** VCardProperty.Encoding not equal to VCdEncoding.QuotedPrintable.
- Then load the vCard again with the specified encoding.

**Comment by HeinzKessler** [comment]
Hi,
thank you for your answers.

The vCard in question comes from MS Outlook (Version M365 16.0). You see the CHARSET parameter in the home address.
I did not want to rely on the existence of a LABEL, which returns the 'ä' correctly, but does not offer separate values for street, Zip and city.

My workaround is similar to your, except that I use a brute force approach and I simply search for the text "CHARSET=" and tke the encoding after the "=", then I reopen the fiole with this encoding.

Example:

```
BEGIN:VCARD
VERSION:2.1
N;LANGUAGE=de:Rastral;Ralf
FN:Ralf Rastral
ADR;HOME;PREF;:;;Lämmerweg 12;Kleindorf;;98765;Deutschland
LABEL;HOME;PREF;CHARSET=Windows-1252;ENCODING=QUOTED-PRINTABLE:L=E4mmerweg 12=0D=0A=
98765 Kleindorf
X-MS-OL-DEFAULT-POSTAL-ADDRESS:1
X-MS-CARDPICTURE;TYPE=JPEG;ENCODING=BASE64:
 /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAcFBQYFBAcGBQYIBwcIChELCgkJChUPEAwRGBUa
 GRgVGBcbHichGx0lHRcYIi4iJSgpKywrGiAvMy8qMicqKyr/2wBDAQcICAoJChQLCxQqHBgc
 KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKir/wAAR
 CACEAB8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
 AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
 FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
 h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
 5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
 AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
 NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
 hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
 5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD37zMsQKGkVB6moR3NNNAEisZH56elJO2A
 AKdEO9RyfPNj0oAU9BTT2pxOTSDlqAJl+VP1qGMZYk1LKdsf6VEOIvc0AFPiGWphqaIYGaAG
 XB5AFMl4VRSt883tmmSnL0AP71KPljyfSolGTzUrjeuB09aAIo+pJpvls7Z6VJhY14+aonkZ
 qALC7T91ajlJzjP4VIg+WovvyfjQAScIBURHpU0mN3zdfQVGXI+7wPagCy3yJ+FRqSx6/TFO
 nPQU1eEzQBG5yxph606mnrQBPKcuaH4jpuNzj3okPSgBlNPWnU09aALCheopHTJ4NCcDJ9c1
 Gf60ABQimlSOop24+tHmH0FAEp4j/Coj0oooASmnrRRQB//Z

X-MS-OL-DESIGN;CHARSET=utf-8:<card xmlns="http://schemas.microsoft.com/office/outlook/12/electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xmlns="" align="fit" area="16" use="cardpicture"/><fld xmlns="" prop="name" align="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="addrhome" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/></card>
REV:20230611T140325Z
END:VCARD

```

**Comment by FolkerKinzel** [comment]
Thanks for the example. 

Unfortunately an automatic solution which would take the CHARSET parameter into account (outside of quoted printable like in the LABEL row) would not really help you, because the ADR;HOME row has no CHARSET parameter. You better should load old vCards from MS Outlook always with an Windows-1252 encoding.

Nevertheless I find your issue interesting and will leave it open. Until now, I've not seen any vCard from the wild which used the CHARSET parameter without QUOTED-PRINTABLE, but it's not completely ruled out that such things exist.

**Comment by HeinzKessler** [comment]
Thanks a lot.
anyhow, I'm happy that I found your component, which covers most of the complexity of this somehow weird file format.

One last question:
Is there a source on the web for vCard files of all kinds and sorts, that I could use to test my part of the code?

**Comment by FolkerKinzel** [comment]
You can use my test files from here:
https://github.com/FolkerKinzel/VCards/tree/master/src/FolkerKinzel.VCards.Tests/TestFiles
and here:
https://github.com/FolkerKinzel/Contacts.IO/tree/master/src/FolkerKinzel.Contacts.IO.Tests/TestFiles

**Comment by FolkerKinzel** [comment]
After reading your interesting issue I did some research. Unfortunately it's not possible to build a mechanism directly in the VCard class, which detects encodings depending on `CHARSET` parameters, because extended ANSI characters are irrecocably lost after once read with UTF-8.
But FolkerKinzel.VCards 5.0.0-beta.1 is now available on nuget. It introduces two new helper classes, `AnsiFilter` and `MultiAnsiFilter`, that automatically load VCF files with the right text encoding if some are among them that use ANSI encodings like in your example above. You can solve the problem now with one line of code:

```csharp
IList<VCard> vCards = new AnsiFilter().LoadVcf(YourExample.vcf);
```

(Windows-1252 is the default fallback encoding of the `AnsiFilter` class.)
